# Generated by Django 4.2.4 on 2023-09-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Migration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_cart", models.CharField(max_length=100)),
                ("target_cart", models.CharField(max_length=100)),
                ("keywords", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=2000)),
            ],
        ),
    ]
