# Generated by Django 4.2.4 on 2023-09-12 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("migration", "0004_migration_date_add_migration_date_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="migration",
            name="date_add",
            field=models.DateField(
                default=datetime.datetime(2023, 9, 12, 10, 50, 22, 464737)
            ),
        ),
        migrations.AlterField(
            model_name="migration",
            name="date_update",
            field=models.DateField(
                default=datetime.datetime(2023, 9, 12, 10, 50, 22, 464737)
            ),
        ),
    ]
