# Generated by Django 4.2.4 on 2023-09-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("migration", "0005_alter_migration_date_add_alter_migration_date_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="migration",
            name="date_add",
            field=models.DateField(default="2023-09-04"),
        ),
        migrations.AlterField(
            model_name="migration",
            name="date_update",
            field=models.DateField(default="2023-09-04"),
        ),
    ]
