# Generated by Django 4.2.4 on 2023-09-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("migration", "0009_migration_date_add_migration_date_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="migration",
            name="date_add",
            field=models.DateField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="migration",
            name="date_update",
            field=models.DateField(blank=True, default=""),
        ),
    ]
