# Generated by Django 4.2.4 on 2023-10-27 08:01

import apps.migration.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('migration', '0011_alter_migration_date_add_alter_migration_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='migration',
            name='user',
            field=models.ForeignKey(default=apps.migration.models.get_tanvv_user_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
