# Generated by Django 4.2.4 on 2023-11-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_type', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=255)),
                ('article', models.TextField(max_length=1000)),
            ],
        ),
    ]
