# Generated by Django 4.2.4 on 2023-08-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("cart_type", models.CharField(max_length=200)),
                ("entity_type", models.CharField(max_length=200)),
                ("method", models.CharField(max_length=200)),
                ("keywords", models.CharField(max_length=200)),
                ("date_add", models.DateField()),
                ("date_update", models.DateField()),
            ],
        ),
    ]
