# Generated by Django 4.2.4 on 2023-08-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_update", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeupdate",
            name="field",
            field=models.CharField(default="", max_length=200),
        ),
    ]
