# Generated by Django 4.2.4 on 2023-08-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_update", "0002_codeupdate_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeupdate",
            name="field",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="codeupdate",
            name="keywords",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
