# Generated by Django 4.2.4 on 2023-09-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_update", "0003_alter_codeupdate_field_alter_codeupdate_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeupdate",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
