# Generated by Django 4.2.4 on 2023-09-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_update", "0004_codeupdate_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeupdate",
            name="keywords",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
