# Generated by Django 4.2.4 on 2023-10-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_update', '0006_alter_codeupdate_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeupdate',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
